labels:
  - name: invalid
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this. Please follow the issue templates and contributing guidelines.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
      discussion:
        body: Thank you @{{ discussion.user.login }} for suggesting this. Please follow the contributing guidelines.
        locking: locked
  
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on, but I appreciate your contribution.
        action: close
      discussion: 
        body: This will not be worked on, but I appreciate your contribution.
        action: answered
        locking: locked
    unlabeled:
      issue:
        action: open
      discussion: 
        action: unanswered
        locking: unlock

  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
      pr:
        body: This issue already exists.
        action: close
      discussion: 
        body: This issue already exists.
        locking: locked
    unlabeled:
      issue:
        body: My apologies. This isn't a duplicate (anymore).
        action: open
      pr:
        body: My apologies. This isn't a duplicate (anymore).
        action: open
      discussion: 
        body: My apologies. This isn't a duplicate (anymore).
        locking: unlock

  - name: can't reproduce
    labeled: 
      issue: 
        body: | 
          Sorry @{{ issue.user.login }}, I can't reproduce your issue. Please give more information (e.g. screenshots)
          or investigate if the problem/issue still occurs.
      discussion: 
        body: | 
          Sorry @{{ discussion.user.login }}, I can't reproduce your issue. Please give more information (e.g. screenshots)
          or investigate if the problem/issue still occurs.
    unlabeled: 
      issue: 
        body: My apologies. I didn't look close enough. I will work on the issue now.
      discussion: 
        body: My apologies. I didn't look close enough. I will work on the issue now.

  - name: off-topic
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of off-topic conversations!
          Please use our other means of communication for casual chats.
        action: close
        locking: lock
        lock_reason: off-topic
      discussion:
        body: |
          This discussion has been **LOCKED** because of off-topic conversations!
          [Please use our other means of communication for casual chats](https://github.com/JohnyP36/Connect4/discussions/categories/ideas). 
        locking: lock

  - name: question
    labeled:
      issue:
        body: Will you look at this, @JohnyP36 ?
  - name: bug
    labeled:
      issue:
        body: Will you look at this, @JohnyP36 ?
